n_features: 50
selected_features:
- ap-96
- diff_1-96
- diff_2-96
- weekofyear-1
- year-0
- hour_cos-1
- hour_sin-0
- hour_cos-0
- weekofyear-6
- short_wave_from_sky_avg-4
- hour-4
- temp_soil_avg_50cm-3
- hour-0
- hour_sin-6
- temp_soil_avg_50cm-1
- weekofyear-7
- ewm_mean-103
- temp_soil_avg_10cm-7
- short_wave_from_sky_avg-5
- hour-1
- sun_int_avg-3
- hour_cos-6
- hour_cos-5
- season_cos-0
- dayofweek_sin-0
- sun_int_avg-7
- temp_soil_avg_5cm-4
- rolling_max-103
- temp_soil_avg_5cm-5
- weekofyear-4
- weekofyear-0
- hour_sin-2
- month-0
- sun_int_avg-2
- temp_soil_avg_50cm-2
- rolling_std-96
- ap-98
- rolling_mean-100
- temp_soil_avg_50cm-6
- sun_int_avg-6
- temp_soil_avg_50cm-0
- dayofweek_sin-1
- hour-3
- day-4
- hour_cos-2
- hour_sin-5
- temp_soil_avg_10cm-0
- rolling_std-102
- pressure-0
- pressure-7
site_id: 4
