n_features: 50
selected_features:
- ewm_mean-96
- rolling_min-96
- ap-96
- rolling_median-96
- is_peak_hour-6
- dayofweek_sin-5
- is_peak_hour-3
- year-5
- hour_cos-3
- month_sin-1
- dayofweek_sin-1
- dayofweek_sin-3
- dayofweek-7
- dayofweek_sin-2
- weekofyear-4
- dayofweek-5
- month_cos-0
- temp_soil_avg_5cm-0
- year-0
- temp_soil_avg_50cm-1
- dayofweek-4
- is_peak_hour-4
- temp_soil_avg_20cm-0
- hour-4
- dayofweek-1
- hour_cos-7
- month_sin-0
- weekofyear-0
- is_peak_hour-7
- hour_sin-3
- year-4
- dayofweek-0
- temp_soil_avg_50cm-4
- dayofweek_sin-7
- temp_soil_avg_20cm-7
- temp_soil_avg_50cm-7
- month_cos-7
- weekofyear-1
- pressure-7
- year-1
- temp_soil_avg-1
- temp_grass_pt100_avg-4
- short_wave_from_sky_avg-2
- short_wave_from_sky_avg-4
- temp_soil_avg-0
- temp_soil_avg_50cm-0
- short_wave_from_sky_avg-3
- temp_soil_avg_50cm-6
- rolling_mean-96
- dayofweek_sin-0
site_id: 7
