n_features: 50
selected_features:
- ap-96
- diff_1-96
- hour_cos-7
- short_wave_from_sky_avg-5
- season_cos-0
- hour_cos-0
- dayofweek_cos-7
- diff_2-96
- dayofweek-7
- sun_int_avg-6
- sun_int_avg-7
- month_cos-0
- season_sin-0
- temp_soil_avg_20cm-3
- month_sin-0
- temp_soil_avg_5cm-4
- sun_int_avg-3
- short_wave_from_sky_avg-4
- weekofyear-7
- temp_soil_avg_20cm-0
- temp_soil_avg_50cm-0
- temp_soil_avg_20cm-5
- dayofweek-3
- pressure-0
- dayofweek-0
- dayofweek_sin-2
- short_wave_from_sky_avg-7
- sun_duration-5
- is_peak_hour-7
- temp_soil_avg_20cm-7
- pressure-2
- dayofweek_cos-0
- short_wave_from_sky_avg-6
- ewm_mean-103
- temp_soil_avg_5cm-5
- month-0
- day-7
- weekofyear-0
- temp_soil_avg_5cm-0
- year-0
- temp_dry_shelter_avg-3
- humidity_rel_shelter_avg-0
- hour_cos-1
- temp_soil_avg_10cm-2
- temp_soil_avg_50cm-4
- season-0
- day-3
- temp_soil_avg_5cm-2
- temp_soil_avg_10cm-3
- temp_soil_avg_10cm-6
site_id: 1
