n_features: 50
selected_features:
- ap-96
- diff_1-96
- short_wave_from_sky_avg-5
- hour_cos-7
- dayofweek_cos-7
- hour_cos-0
- diff_2-96
- season_cos-0
- sun_int_avg-6
- dayofweek_sin-2
- season_sin-0
- sun_int_avg-7
- dayofweek-3
- month_cos-0
- short_wave_from_sky_avg-7
- dayofweek-7
- temp_soil_avg_20cm-0
- temp_soil_avg_20cm-3
- temp_soil_avg_50cm-5
- weekofyear-7
- month_sin-0
- temp_soil_avg_50cm-0
- sun_int_avg-3
- year-0
- pressure-0
- dayofweek-0
- short_wave_from_sky_avg-4
- temp_soil_avg_5cm-5
- temp_soil_avg_20cm-5
- day-7
- pressure-2
- temp_soil_avg_5cm-0
- temp_soil_avg_20cm-7
- temp_soil_avg_10cm-2
- temp_soil_avg_5cm-4
- ewm_mean-103
- temp_soil_avg_50cm-2
- temp_dry_shelter_avg-3
- weekofyear-0
- season-0
- day-3
- hour_cos-3
- temp_soil_avg_10cm-6
- month-0
- humidity_rel_shelter_avg-0
- short_wave_from_sky_avg-6
- short_wave_from_sky_avg-1
- sun_int_avg-2
- hour_cos-1
- is_peak_hour-1
site_id: 3
