n_features: 50
selected_features:
- ap-96
- diff_1-96
- hour_cos-7
- short_wave_from_sky_avg-5
- dayofweek_cos-7
- diff_2-96
- hour_cos-0
- season_cos-0
- sun_int_avg-6
- month_cos-0
- sun_int_avg-7
- hour_cos-5
- dayofweek-3
- temp_soil_avg_50cm-0
- dayofweek-7
- season_sin-0
- month_sin-0
- weekofyear-7
- temp_soil_avg_20cm-0
- temp_soil_avg_20cm-3
- short_wave_from_sky_avg-7
- short_wave_from_sky_avg-4
- sun_int_avg-3
- dayofweek-0
- temp_soil_avg_50cm-4
- pressure-0
- day-7
- temp_soil_avg_20cm-7
- pressure-2
- temp_soil_avg_10cm-5
- temp_soil_avg_5cm-0
- temp_soil_avg_5cm-5
- weekofyear-0
- temp_soil_avg_50cm-2
- temp_soil_avg_5cm-2
- temp_soil_avg_10cm-6
- temp_soil_avg_5cm-4
- day-3
- hour_sin-6
- month-0
- ewm_mean-103
- temp_soil_avg_20cm-5
- dayofweek_sin-1
- hour_cos-3
- pressure-7
- temp_dry_shelter_avg-3
- sun_int_avg-2
- day-0
- temp_dry_shelter_avg-6
- short_wave_from_sky_avg-0
site_id: 5
