n_features: 50
selected_features:
- rolling_min-96
- is_peak_hour-1
- temp_soil_avg_5cm-1
- temp_soil_avg_5cm-4
- dayofweek_sin-4
- ap-96
- is_peak_hour-0
- hour_sin-7
- dayofweek_sin-0
- temp_soil_avg_5cm-3
- dayofweek_sin-7
- rolling_median-96
- is_peak_hour-2
- short_wave_from_sky_avg-7
- hour_cos-0
- is_peak_hour-4
- dayofweek-4
- temp_soil_avg_20cm-0
- temp_soil_avg-7
- dayofweek-0
- dayofweek-3
- temp_grass_pt100_avg-7
- temp_soil_avg-6
- hour_cos-3
- temp_soil_avg_5cm-0
- month-0
- year-0
- temp_dry_shelter_avg-7
- short_wave_from_sky_avg-5
- hour-2
- ewm_mean-96
- dayofweek-6
- hour_cos-1
- dayofweek_sin-5
- temp_soil_avg-1
- year-4
- hour-0
- hour-1
- hour-3
- temp_dry_shelter_avg-1
- sun_int_avg-4
- season_cos-7
- ewm_mean-101
- is_peak_hour-3
- weekofyear-0
- month_cos-0
- humidity_rel_shelter_avg-4
- rolling_min-101
- temp_grass_pt100_avg-6
- short_wave_from_sky_avg-6
site_id: 6
