n_features: 50
selected_features:
- ap-96
- diff_1-96
- hour_cos-7
- short_wave_from_sky_avg-5
- hour_cos-0
- diff_2-96
- dayofweek_cos-7
- sun_int_avg-6
- season_sin-0
- dayofweek_sin-3
- month_cos-0
- sun_int_avg-7
- short_wave_from_sky_avg-4
- dayofweek-7
- month-0
- sun_int_avg-3
- temp_soil_avg_20cm-7
- temp_soil_avg_20cm-5
- pressure-0
- short_wave_from_sky_avg-7
- dayofweek_sin-0
- pressure-3
- temp_soil_avg_50cm-0
- temp_soil_avg_20cm-0
- temp_soil_avg_10cm-1
- month_sin-0
- season-1
- dayofweek_sin-4
- day-7
- year-0
- temp_soil_avg_20cm-6
- season-0
- weekofyear-0
- is_peak_hour-3
- pressure-6
- temp_soil_avg_5cm-5
- weekofyear-7
- hour_cos-2
- temp_soil_avg_5cm-0
- hour-4
- ewm_mean-103
- hour_cos-1
- humidity_rel_shelter_avg-0
- temp_soil_avg-4
- day-0
- short_wave_from_sky_avg-6
- sun_int_avg-2
- dayofweek-0
- temp_dry_shelter_avg-3
- temp_dry_shelter_avg-1
site_id: 2
