"""
Optimization pipeline for production/consumption constraints.

Given predictions for consumption and production across sites, this pipeline:
1. Maximizes total production
2. Ensures production <= consumption per site
3. Indicates which sites should be disabled if constraints are violated
"""

__title__: str = "optimization_pipeline"
__version__: str = "1.0.0"
__author__: str = "Brice Petit"
__license__: str = "MIT"

# ----------------------------------------------------------------------------------------------- #
# ------------------------------------------- IMPORTS ------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #

# Imports from standard library
import logging
from pathlib import Path
from typing import Any

# Imports from third party libraries
import numpy as np
import pandas as pd
import yaml
from scipy.optimize import milp, LinearConstraint, Bounds

# Imports from src
from configs.config_loader import ConfigLoader
from utils.logging import setup_logger

# ----------------------------------------------------------------------------------------------- #
# ----------------------------------------- Globals --------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #

logger = logging.getLogger(__name__)
if not logging.getLogger().handlers:
    setup_logger(log_file="optimization_pipeline.log", level=logging.INFO)

config_loader = ConfigLoader()
config = config_loader.load_global()

DASH = '-' * 20

# ----------------------------------------------------------------------------------------------- #
# ------------------------------------------ Functions ------------------------------------------ #
# ----------------------------------------------------------------------------------------------- #


def _get_predictions_root() -> Path:
    """
    Resolve predictions root directory consistently with inference pipeline.

    :return: Path to predictions root.
    """
    configured_root = config['paths']['paths'].get('predictions_dir')
    if configured_root:
        return Path(configured_root)
    return Path("src/predictions")


def load_predictions_from_yaml(etype: str, site_id: int) -> pd.DataFrame | None:
    """
    Load predictions saved as YAML from inference pipeline.

    :param etype:   Energy type (consumption or production).
    :param site_id: Site ID.

    :return:        DataFrame with predictions or None if file not found.
    """
    prediction_path = _get_predictions_root() / etype / f"site_{site_id}.yaml"
    if not prediction_path.exists():
        logger.warning("Prediction file not found: %s", prediction_path)
        return None

    with open(prediction_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not data:
        return None

    df = pd.DataFrame(data)
    if df.empty:
        return None

    # Optimization must use the latest available snapshot point only.
    if "ts" in df.columns:
        df["ts"] = pd.to_datetime(df["ts"], errors="coerce")
        df = df.dropna(subset=["ts"]).sort_values("ts")
        if df.empty:
            return None
        df = df.tail(1)

    return df.reset_index(drop=True)


def load_synthetic_consumption_now() -> float:
    """
    Load latest synthetic household consumption power (W) from CSV generated by data pipeline.

    :return: Latest synthetic power in watts, or 0.0 if unavailable.
    """
    processed_dir = config['paths']['paths']['processed_data_dir']
    csv_path = Path(processed_dir) / "synthetic_consumption_w.csv"
    if not csv_path.exists():
        logger.warning("Synthetic consumption curve not found: %s", csv_path)
        return 0.0

    df = pd.read_csv(csv_path)
    if df.empty or "power_w" not in df.columns:
        logger.warning("Synthetic consumption CSV missing required column power_w: %s", csv_path)
        return 0.0

    if "ts" in df.columns:
        df["ts"] = pd.to_datetime(df["ts"], errors="coerce")
        df = df.dropna(subset=["ts"]).sort_values("ts")
    if df.empty:
        return 0.0

    value = pd.to_numeric(df.iloc[-1]["power_w"], errors="coerce")
    if pd.isna(value):
        return 0.0
    return float(max(value, 0.0))


def optimize_production(
    cons_predictions: pd.DataFrame,
    prod_predictions: pd.DataFrame,
    synthetic_consumption_w: float = 0.0,
) -> tuple[dict[str, Any], np.ndarray, np.ndarray]:
    """
    Solve MILP optimization problem to maximize production subject to constraints.

    Maximize: sum(prod_actual[i])
    Subject to:
      - prod_actual[i] <= prod_pred[i] * active[i]  (production limited by forecast & activity)
      - prod_actual[i] <= cons_pred[i]              (production cannot exceed consumption)
      - active[i] in {0, 1}                         (binary: site active or disabled)

    :param cons_predictions:    DataFrame with consumption predictions
                                (columns: pred_t+1, pred_t+2, ...)
    :param prod_predictions:    DataFrame with production predictions
                                (columns: pred_t+1, pred_t+2, ...)
    :param synthetic_consumption_w:
                                Additional synthetic household consumption demand in watts.
    :return:                    Tuple of (solution_dict, prod_actual, active)
    """
    if cons_predictions.empty or prod_predictions.empty:
        raise ValueError("Empty prediction DataFrames provided")

    # Use first prediction horizon (pred_t+1) for optimization
    target_col = "pred_t+1"
    if target_col not in cons_predictions.columns or target_col not in prod_predictions.columns:
        raise ValueError(f"Expected column '{target_col}' not found in predictions")

    cons_pred = cons_predictions[target_col].values
    prod_pred = prod_predictions[target_col].values

    if len(cons_pred) != len(prod_pred):
        raise ValueError("Consumption and production predictions have different lengths")

    n_sites = len(cons_pred)

    # Decision variables: [prod_actual[0], ..., prod_actual[n-1], active[0], ..., active[n-1]]
    # Total: 2*n variables
    n_vars = 2 * n_sites

    # Objective: maximize sum(prod_actual[i])  =>  minimize -sum(prod_actual[i])
    c = np.zeros(n_vars)
    c[:n_sites] = -1.0  # Negative for maximization

    # Build constraints: A_ub @ x <= b_ub
    # Constraint 1: prod_actual[i] <= cons_pred[i]
    # Constraint 2: prod_actual[i] <= prod_pred[i] * active[i]
    #            => prod_actual[i] - prod_pred[i]*active[i] <= 0
    # Constraint 3: sum(prod_actual) <= sum(cons_pred) + synthetic_consumption_w

    A_constraints = []
    b_constraints = []

    # Constraint 1: prod_actual[i] <= cons_pred[i]
    for i in range(n_sites):
        row = np.zeros(n_vars)
        row[i] = 1.0
        A_constraints.append(row)
        b_constraints.append(cons_pred[i])

    # Constraint 2: prod_actual[i] - prod_pred[i]*active[i] <= 0
    for i in range(n_sites):
        row = np.zeros(n_vars)
        row[i] = 1.0
        row[n_sites + i] = -prod_pred[i]
        A_constraints.append(row)
        b_constraints.append(0.0)

    # Constraint 3: global production capped by measured + synthetic consumption demand
    global_row = np.zeros(n_vars)
    global_row[:n_sites] = 1.0
    A_constraints.append(global_row)
    b_constraints.append(float(np.sum(cons_pred) + max(synthetic_consumption_w, 0.0)))

    A_ub = np.array(A_constraints)
    b_ub = np.array(b_constraints)

    # Bounds: prod_actual >= 0, active in [0, 1]
    bounds = Bounds(
        lb=np.concatenate([np.zeros(n_sites), np.zeros(n_sites)]),
        ub=np.concatenate([np.inf * np.ones(n_sites), np.ones(n_sites)])
    )

    # Specify that variables n_sites:n_vars are binary (the 'active' variables)
    integrality = np.zeros(n_vars)
    integrality[n_sites:] = 1  # Binary constraint for active[i]

    # Solve MILP
    constraint = LinearConstraint(A_ub, -np.inf, b_ub)

    try:
        result = milp(
            c=c,
            constraints=constraint,
            bounds=bounds,
            integrality=integrality,
            options={"disp": False}
        )

        if not result.success:
            logger.warning("MILP solver did not converge: %s", result.message)

        prod_actual = result.x[:n_sites]
        active = result.x[n_sites:].astype(int)

        return {
            "success": result.success,
            "objective": -result.fun,  # Negate back
        }, prod_actual, active

    except Exception as e:
        logger.exception("MILP optimization failed: %s", str(e))
        raise


def run_optimization_pipeline(
    site_ids: list[int] | None = None,
    include_synthetic_consumption: bool = True,
    save_results: bool = True,
) -> dict[str, Any]:
    """
    Run optimization across all or specified production sites.

    :param site_ids:        List of site IDs to optimize. If None, use all from config.
    :param include_synthetic_consumption:
                            If True, include latest synthetic household demand in constraints.
    :param save_results:    Save optimization results to YAML.
        
    :return:                Dictionary with results and disabled sites recommendations.
    """
    logger.info("%s Starting optimization pipeline %s", DASH, DASH)

    production_sites = config['domain']['production_sites_grouped']
    target_site_ids = site_ids if site_ids else list(production_sites.keys())

    all_results = {
        "timestamp": pd.Timestamp.now().isoformat(),
        "sites": {},
        "disabled_sites": [],
        "total_production_optimized": 0.0,
    }

    synthetic_consumption_w = load_synthetic_consumption_now() if include_synthetic_consumption else 0.0
    all_results["synthetic_consumption_w"] = synthetic_consumption_w

    for site_id in target_site_ids:
        try:
            logger.info("%s Optimizing site_id=%s %s", DASH, site_id, DASH)

            # Load predictions for consumption and production
            cons_pred = load_predictions_from_yaml("consumption", site_id)
            prod_pred = load_predictions_from_yaml("production", site_id)

            if cons_pred is None or prod_pred is None:
                logger.warning("Could not load predictions for site_id=%s", site_id)
                all_results["sites"][site_id] = {
                    "status": "error",
                    "message": "Missing consumption or production predictions"
                }
                continue

            # Solve optimization problem
            solution, prod_actual, active = optimize_production(
                cons_pred,
                prod_pred,
                synthetic_consumption_w=synthetic_consumption_w,
            )

            # Identify disabled sites
            disabled = [i for i in range(len(active)) if active[i] == 0]
            disabled_site_names = []
            if disabled and site_id in production_sites:
                site_list = production_sites[site_id]
                disabled_site_names = [site_list[i] for i in disabled if i < len(site_list)]

            total_prod = float(np.sum(prod_actual))
            all_results["sites"][site_id] = {
                "status": "success",
                "total_production_optimized": total_prod,
                "n_sites_active": int(np.sum(active)),
                "n_sites_disabled": len(disabled),
                "disabled_sites": disabled_site_names,
                "optimization_success": bool(solution["success"]),
                "objective_value": float(solution["objective"]),
            }

            all_results["total_production_optimized"] += total_prod
            if disabled:
                all_results["disabled_sites"].extend(disabled_site_names)

            logger.info(
                "Site %s optimized: prod=%f, active=%d, disabled=%d",
                site_id,
                total_prod,
                int(np.sum(active)),
                len(disabled)
            )

        except Exception as exc:
            logger.exception("Optimization failed for site_id=%s: %s", site_id, exc)
            all_results["sites"][site_id] = {
                "status": "error",
                "message": str(exc)
            }

    # Save results
    if save_results:
        output_path = Path("src/configs/optimization_results.yaml")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            yaml.dump(all_results, f, default_flow_style=False)
        logger.info("Optimization results saved to %s", output_path)
        all_results["output_path"] = str(output_path)

    logger.info("%s Optimization pipeline completed %s", DASH, DASH)
    return all_results


if __name__ == "__main__":
    run_optimization_pipeline()
