n_features: 50
selected_features:
- temp_grass_pt100_avg-6
- temp_grass_pt100_avg-7
- short_wave_from_sky_avg-7
- hour_cos-7
- short_wave_from_sky_avg-6
- month_cos-0
- hour_cos-5
- short_wave_from_sky_avg-5
- temp_soil_avg_5cm-6
- rolling_mean-103
- rolling_median-97
- ap-96
- hour_cos-4
- dayofweek-0
- humidity_rel_shelter_avg-7
- humidity_rel_shelter_avg-4
- temp_soil_avg-7
- temp_soil_avg-6
- temp_soil_avg_50cm-2
- temp_grass_pt100_avg-2
- is_peak_hour-7
- season_cos-0
- hour_cos-6
- is_peak_hour-3
- temp_soil_avg_50cm-7
- rolling_max-96
- temp_soil_avg_5cm-7
- temp_soil_avg_5cm-3
- short_wave_from_sky_avg-4
- ewm_mean-96
- rolling_max-97
- rolling_min-103
- temp_dry_shelter_avg-4
- temp_soil_avg_20cm-3
- hour-2
- weekofyear-0
- temp_soil_avg-4
- ewm_mean-100
- temp_soil_avg_20cm-7
- hour_cos-0
- temp_soil_avg_20cm-4
- pressure-7
- sun_duration-1
- rolling_mean-101
- temp_soil_avg_5cm-4
- temp_dry_shelter_avg-2
- temp_soil_avg_20cm-2
- short_wave_from_sky_avg-2
- rolling_min-100
- short_wave_from_sky_avg-1
site_id: 5
