n_features: 50
selected_features:
- short_wave_from_sky_avg-7
- short_wave_from_sky_avg-6
- short_wave_from_sky_avg-5
- month_cos-0
- humidity_rel_shelter_avg-0
- short_wave_from_sky_avg-4
- humidity_rel_shelter_avg-1
- rolling_mean-96
- humidity_rel_shelter_avg-7
- short_wave_from_sky_avg-3
- rolling_max-100
- rolling_max-96
- ewm_mean-97
- ewm_mean-96
- year-0
- rolling_median-97
- hour_cos-2
- temp_grass_pt100_avg-0
- hour_cos-5
- temp_soil_avg_10cm-2
- temp_soil_avg_20cm-7
- humidity_rel_shelter_avg-4
- pressure-0
- ewm_mean-103
- short_wave_from_sky_avg-2
- sun_int_avg-0
- rolling_median-102
- ap-96
- rolling_mean-103
- temp_soil_avg-7
- month_sin-0
- short_wave_from_sky_avg-0
- hour-1
- rolling_min-99
- hour-3
- rolling_max-97
- dayofweek_sin-0
- temp_dry_shelter_avg-7
- rolling_median-103
- humidity_rel_shelter_avg-3
- temp_soil_avg_50cm-4
- rolling_std-96
- sun_duration-0
- temp_soil_avg_50cm-1
- temp_soil_avg-3
- temp_soil_avg_50cm-7
- is_peak_hour-7
- precip_quantity-3
- temp_soil_avg_20cm-4
- rolling_max-103
site_id: 4
