n_features: 50
selected_features:
- short_wave_from_sky_avg-5
- short_wave_from_sky_avg-6
- short_wave_from_sky_avg-4
- short_wave_from_sky_avg-3
- hour_cos-4
- hour_cos-1
- hour_cos-0
- short_wave_from_sky_avg-7
- sun_int_avg-7
- hour_cos-3
- short_wave_from_sky_avg-2
- short_wave_from_sky_avg-0
- humidity_rel_shelter_avg-7
- season_sin-0
- hour_cos-5
- hour_cos-2
- humidity_rel_shelter_avg-1
- hour-0
- short_wave_from_sky_avg-1
- temp_soil_avg_50cm-2
- humidity_rel_shelter_avg-5
- temp_soil_avg-7
- humidity_rel_shelter_avg-0
- year-0
- humidity_rel_shelter_avg-6
- hour-3
- humidity_rel_shelter_avg-3
- month_cos-0
- sun_duration-7
- temp_dry_shelter_avg-7
- rolling_median-96
- hour_cos-6
- pressure-1
- precip_quantity-3
- ewm_mean-96
- temp_soil_avg_20cm-7
- pressure-3
- dayofweek_sin-7
- is_peak_hour-7
- pressure-2
- weekofyear-0
- hour-1
- sun_int_avg-0
- month_sin-0
- dayofweek_cos-0
- hour-2
- rolling_max-96
- rolling_mean-97
- rolling_max-102
- temp_soil_avg_50cm-3
site_id: 3
