n_features: 50
selected_features:
- short_wave_from_sky_avg-7
- hour_cos-2
- hour_cos-3
- hour_cos-4
- hour_cos-5
- hour_cos-0
- temp_grass_pt100_avg-7
- temp_grass_pt100_avg-4
- rolling_max-99
- rolling_median-100
- dayofweek_sin-0
- rolling_max-103
- temp_grass_pt100_avg-6
- rolling_min-102
- short_wave_from_sky_avg-6
- wind_speed_avg_30m-4
- rolling_mean-97
- temp_grass_pt100_avg-1
- rolling_max-102
- hour-1
- hour_cos-6
- rolling_min-101
- temp_soil_avg_10cm-6
- day-0
- rolling_std-100
- temp_soil_avg_5cm-5
- sun_duration-6
- short_wave_from_sky_avg-5
- sun_int_avg-1
- humidity_rel_shelter_avg-5
- ewm_mean-98
- sun_int_avg-6
- temp_soil_avg-7
- short_wave_from_sky_avg-1
- wind_speed_avg_30m-5
- short_wave_from_sky_avg-4
- temp_soil_avg_50cm-5
- temp_soil_avg_10cm-5
- rolling_std-99
- sun_int_avg-5
- temp_soil_avg_10cm-3
- sun_duration-3
- short_wave_from_sky_avg-0
- wind_gusts_speed-4
- temp_soil_avg_50cm-7
- pressure-5
- rolling_std-98
- temp_soil_avg_5cm-3
- wind_gusts_speed-6
- humidity_rel_shelter_avg-3
site_id: 6
